# Generated by Django 5.1 on 2024-08-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default_course_img.jpg', upload_to='')),
                ('short_discription', models.TextField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('count_videos', models.IntegerField(default=0)),
                ('time_video', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
    ]
